package handlers

import (
	"LiteAdmin/models"
	"LiteAdmin/services"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/labstack/echo/v4"
)

type AuthHandler struct {
	authService  *services.AuthService
	oauthService *services.OAuthService
}

func NewAuthHandler(authService *services.AuthService, oauthService *services.OAuthService) *AuthHandler {
	return &AuthHandler{
		authService:  authService,
		oauthService: oauthService,
	}
}

// Get available OAuth providers

func (h *AuthHandler) GetProviders(c echo.Context) error {
	providers := h.oauthService.GetAvailableProviders()
	return c.JSON(http.StatusOK, map[string]interface{}{
		"providers": providers,
	})
}

// Start OAuth flow

func (h *AuthHandler) OAuthLogin(c echo.Context) error {
	provider := c.Param("provider")
	state := c.QueryParam("state") // Should be generated by frontend for CSRF protection
	userType := c.QueryParam("type")
	combinedState := fmt.Sprintf("%s|%s", state, userType)
	authURL, err := h.oauthService.GetAuthURL(provider, combinedState)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": err.Error(),
		})
	}
	fmt.Println("authURL:", authURL)
	return c.JSON(http.StatusOK, map[string]string{
		"auth_url": authURL,
	})
}

// 根据token信息获取用户信息

func (h *AuthHandler) OAuthCallback(c echo.Context) error {
	provider := c.Param("provider")
	code := c.QueryParam("code")
	state := c.QueryParam("state")
	_, userType, _ := strings.Cut(state, "|")
	// Exchange code for token
	token, err := h.oauthService.ExchangeCode(provider, code)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": "failed to exchange code",
		})
	}

	// Get user info
	userInfo, err := h.oauthService.GetUserInfo(provider, token)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to get user info",
		})
	}

	// Find or create user
	user, err := h.authService.FindOrCreateOAuthUser(userInfo, userType)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to create user",
		})
	}

	// Generate JWT tokens
	authResponse, err := h.authService.GenerateTokens(user)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to generate tokens",
		})
	}

	return c.JSON(http.StatusOK, authResponse)
}

// Local registration
func (h *AuthHandler) Register(c echo.Context) error {
	var req struct {
		Email    string `json:"email" validate:"required,email"`
		Username string `json:"username" validate:"required"`
		Password string `json:"password" validate:"required,min=8"`
	}

	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": "invalid request",
		})
	}

	user, err := h.authService.RegisterLocal(req.Email, req.Username, req.Password)
	if err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": err.Error(),
		})
	}

	authResponse, err := h.authService.GenerateTokens(user)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to generate tokens",
		})
	}

	return c.JSON(http.StatusCreated, authResponse)
}

// Local login
func (h *AuthHandler) Login(c echo.Context) error {
	var req struct {
		Email      string `json:"email" validate:"required,email"`
		Password   string `json:"password" validate:"required"`
		RememberMe bool   `json:"rememberMe"`
	}

	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": "invalid request",
		})
	}

	user, err := h.authService.LoginLocal(req.Email, req.Password)
	if err != nil {
		return c.JSON(http.StatusUnauthorized, map[string]string{
			"error": err.Error(),
		})
	}

	authResponse, err := h.authService.GenerateTokens(user)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to generate tokens",
		})
	}
	// 处理记住我功能
	if req.RememberMe {
		emailCookie := &http.Cookie{
			Name:     "remembered_email",
			Value:    req.Email,
			Path:     "/",
			Expires:  time.Now().Add(3 * 24 * time.Hour), // 3天
			HttpOnly: false,
			Secure:   true,
			SameSite: http.SameSiteLaxMode,
		}
		passwordCookie := &http.Cookie{
			Name:     "remembered_password",
			Value:    req.Email,
			Path:     "/",
			Expires:  time.Now().Add(3 * 24 * time.Hour), // 3天
			HttpOnly: false,
			Secure:   true,
			SameSite: http.SameSiteLaxMode,
		}
		c.SetCookie(passwordCookie)
		c.SetCookie(emailCookie)
	} else {
		// 如果不勾选记住我，清除之前的 Cookie
		emailCookie := &http.Cookie{
			Name:     "remembered_email",
			Value:    "",
			Path:     "/",
			Expires:  time.Now().Add(-1 * time.Hour), // 设置过期时间为过去
			MaxAge:   -1,
			HttpOnly: false,
			Secure:   true,
			SameSite: http.SameSiteLaxMode,
		}
		c.SetCookie(emailCookie)
		passwordCookie := &http.Cookie{
			Name:     "remembered_password",
			Value:    "",
			Path:     "/",
			Expires:  time.Now().Add(-1 * time.Hour), // 设置过期时间为过去
			MaxAge:   -1,
			HttpOnly: false,
			Secure:   true,
			SameSite: http.SameSiteLaxMode,
		}
		c.SetCookie(passwordCookie)
	}
	return c.JSON(http.StatusOK, authResponse)
}

// Refresh token
func (h *AuthHandler) RefreshToken(c echo.Context) error {
	var req struct {
		RefreshToken string `json:"refresh_token" validate:"required"`
	}

	if err := c.Bind(&req); err != nil {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": "invalid request",
		})
	}

	claims, err := h.authService.ValidateToken(req.RefreshToken)
	if err != nil {
		return c.JSON(http.StatusUnauthorized, map[string]string{
			"error": "invalid token",
		})
	}

	var user models.User
	if err := h.authService.Db.First(&user, claims.UserID).Error; err != nil {
		return c.JSON(http.StatusNotFound, map[string]string{
			"error": "user not found",
		})
	}

	authResponse, err := h.authService.GenerateTokens(&user)
	if err != nil {
		return c.JSON(http.StatusInternalServerError, map[string]string{
			"error": "failed to generate tokens",
		})
	}

	return c.JSON(http.StatusOK, authResponse)
}

// Get current user
func (h *AuthHandler) GetCurrentUser(c echo.Context) error {
	user := c.Get("user").(*models.User)
	return c.JSON(http.StatusOK, user)
}
